server:
   port: 8001
spring:
   application:
      name: sc-user
      
eureka:
   client:
      serviceUrl:
         #注册服务器
         defaultZone: http://127.0.0.1:8100/eureka,http://127.0.0.1:8200/eureka
  
# java 运行参数：--spring.profiles.active=cu1
#  mvn 运行参数：-Dspring.profiles.active=cu1
# yml 分区配置

---
# 分区配置名称
spring:
   profiles: cu1
server:
   port: 8100
eureka:
   client:
      serviceUrl:
         #注册服务器
         defaultZone: http://127.0.0.1:8000/eureka,http://127.0.0.1:8200/eureka
spring:
   profiles: cu2
server:
   port: 8200
eureka:
   client:
      serviceUrl:
         #注册服务器
         defaultZone: http://127.0.0.1:8100/eureka,http://127.0.0.1:8000/eureka
   