#server.port=80
#server.port.a=true
#server.port.b=true
#自定义参数
myUploadPath: D:/other/javaExample/
server:
   port: 80
spring:
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/C76-S3-Psq-blog
      username: root
      password: a
      driver-class-name: com.mysql.jdbc.Driver
   #静态资源映射
   resources:
      staticLocations:
         - classpath:/resources/
         - classpath:/static/
         - file:${myUploadPath}
   #文件上传配置
   servlet:
      multipart:
         maxFileSize:10000000000
   mail:
      #邮箱服务器地址
      host: smtp.qq.com
      #用户名
      username: 1139386771@qq.com
      #密码
      password: pzppfeouxbjdfiah
      #字符集编码
      default-encoding: UTF-8
 
#以谁来发送邮件，自定义参数
mail:
   fromMail:
      addr: 1139386771@qq.com
         
#mvc:
mybatis:
   type-aliases-package: com.yc.blog.bean
# view:
#   prefix: WEB-INF/page/
#   suffix: .jsp
   configuration:
      map-underscore-to-camel-case: true
#实体类的路径
# 日志配置
logging:
   level:
      com:
         yc:
            blog:
               dao: debug
               web: warn