server:
   port: 80
spring:
   application:
      name: sc-index
      
eureka:
   client:
      serviceUrl:
         #注册服务器
         defaultZone: http://127.0.0.1:8000/eureka
#开启声明式熔断降级开关
feign:
   hystrix:
      enabled: true